"""empty message

Revision ID: 2c483974cf61
Revises: 56cf69a8bfb5
Create Date: 2020-03-19 19:43:38.027368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c483974cf61'
down_revision = '56cf69a8bfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Donor', sa.Column('donation', sa.Integer(), nullable=True))
    op.drop_column('Donor', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Donor', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('Donor', 'donation')
    # ### end Alembic commands ###
