"""empty message

Revision ID: 56cf69a8bfb5
Revises: 
Create Date: 2020-03-19 19:08:50.028781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cf69a8bfb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Donor', 'num_products')
    op.drop_column('Donor', 'products')
    op.drop_column('Donor', 'blood_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Donor', sa.Column('blood_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Donor', sa.Column('products', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Donor', sa.Column('num_products', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
