"""empty message

Revision ID: cbb6fa698e38
Revises: 2c483974cf61
Create Date: 2020-03-19 20:36:01.947303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb6fa698e38'
down_revision = '2c483974cf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Product_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('cell_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_processing', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Product_pkey')
    )
    # ### end Alembic commands ###
